# Generated by Django 4.2 on 2023-11-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(related_name='dishes', to='core.tag', verbose_name='Теги'),
        ),
    ]
