# Generated by Django 4.2 on 2023-11-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dish_category_alter_dish_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=True, verbose_name='Выполнен')),
                ('created_on', models.DateField(auto_now_add=True, help_text='Когда был создан', verbose_name='создан')),
                ('dishes', models.ManyToManyField(related_name='orders', to='core.dish', verbose_name='Заказы')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.table', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
