# Generated by Django 4.2 on 2023-11-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Забронирован'),
        ),
    ]
