# Generated by Django 4.2 on 2023-11-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
    ]
