# Generated by Django 4.2 on 2023-11-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_dishes_orderdish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdish',
            options={'verbose_name': 'блюдо в заказ', 'verbose_name_plural': 'Блюда в заказе'},
        ),
        migrations.AddField(
            model_name='orderdish',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Готово'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dishes', to='core.dish', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
