# Generated by Django 4.2 on 2023-11-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_orderdish_options_orderdish_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
