# Generated by Django 4.2 on 2023-11-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_is_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс 150 символов', max_length=150, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='DishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс 150 символов', max_length=150, verbose_name='Имя')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='Масса в граммах')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.dish', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'продукт в блюде',
                'verbose_name_plural': 'продукты в блюде',
            },
        ),
    ]
