# Generated by Django 4.2 on 2023-11-20 09:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_dishproduct_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='main_image',
            field=sorl.thumbnail.fields.ImageField(default='', help_text='Любая картинка, вам же на неё смотреть...', upload_to='uploads/', verbose_name='Основная картинка'),
        ),
    ]
